spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/soundforge
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

application:
  security:
    jwt:
      secret-key: Uffoqc160ErPQYsNqdReOmaosSSyl4roKnNaENg1VVaeUveRoVB4v1Q57a52OOik
      expiration: 3600000

server:
  port: 8088
